# Generated by Django 3.2.10 on 2022-05-25 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('people_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.peoplearticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DirectorComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('director_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.directorarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActorComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('actor_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.actorarticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
